// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID             pgtype.UUID
	EventID        pgtype.UUID
	UserID         pgtype.UUID
	Seats          int32
	SeatIds        []pgtype.UUID
	Status         string
	IdempotencyKey pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Event struct {
	ID          pgtype.UUID
	Name        string
	Venue       pgtype.Text
	StartTime   pgtype.Timestamptz
	Capacity    int32
	BookedCount int32
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Seat struct {
	ID            pgtype.UUID
	EventID       pgtype.UUID
	SeatNo        string
	Status        string
	BookingID     pgtype.UUID
	HoldExpiresAt pgtype.Timestamptz
	HoldToken     pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type SeatHold struct {
	ID        pgtype.UUID
	HoldToken string
	EventID   pgtype.UUID
	UserID    pgtype.UUID
	SeatIds   []pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	Status    string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Password  string
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Waitlist struct {
	ID             pgtype.UUID
	EventID        pgtype.UUID
	UserID         pgtype.UUID
	RequestedSeats int32
	Position       int64
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
